id: A494499C4
title: Prayer for the Long Life of His Holiness the Dalai Lama
type: translation
pechas:
- I1F747D38
- I1E440841
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:49:44.351890
  last_modified_at: 2023-01-04 12:49:44.351907
  collections:
  - Khenchen Jigme Phuntsok Series
  - Works of Tibetan Masters
alignment_to_base:
  I1F747D38/BD58: BB8B
  I1E440841/40A4: BB8B
